# This is a basic workflow that is manually triggered

name: Staging Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  staging_deploy:
    name: Staging Deploy
    runs-on: ubuntu-20.04 # ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: git fetch --no-tags --prune origin +refs/heads/*:refs/remotes/origin/*
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Gem Cache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup gems
        run: |
          gem install bundler
          bundle install --jobs 4 --path vendor/bundle
      - name: Deploy
        env:
          SERVER_PUBLIC_IP: ${{secrets.SERVER_PUBLIC_IP}}
          SSH_KEY: ${{secrets.SSH_KEY}}
        run: |
          echo $SSH_KEY > ~/ssh_key.pem
          bundle exec cap staging deploy



